main_1.o: main_1.c
	gcc -c main_1.c
main_1: main_1.o
	gcc -o main_1 main_1.o
main_2.o: main_2.c
	gcc -c main_2.c
main_2: main_2.o
	gcc -o main_2 main_2.o
main_3.o: main_3.c
	gcc -c main_3.c
clean:
	rm -f *.o main
