all: task13.exe
task13.o: task13.c
	gcc -c task13.c
task13: task13.o
	gcc  task13.o
task14.o: task14.c
	gcc -c task14.c
task14: task14.o
	gcc  task14.o
task15.o: task15.c
	gcc -c task15.c
task15: task15.o
	gcc  task15.o
task16.o: task16.c
	gcc -c task16.c
task16: task16.o
	gcc  task16.o
clean:
	rm -f *.o a.out
